/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/verification`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/app`; params?: Router.UnknownInputParams; } | { pathname: `/app/login`; params?: Router.UnknownInputParams; } | { pathname: `/app/matching`; params?: Router.UnknownInputParams; } | { pathname: `/app/settings`; params?: Router.UnknownInputParams; } | { pathname: `/app/signup`; params?: Router.UnknownInputParams; } | { pathname: `/app/tracking`; params?: Router.UnknownInputParams; } | { pathname: `/app/verification`; params?: Router.UnknownInputParams; } | { pathname: `/app/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/app${'/(tabs)'}/activity` | `/app/activity`; params?: Router.UnknownInputParams; } | { pathname: `/app${'/(tabs)'}` | `/app`; params?: Router.UnknownInputParams; } | { pathname: `/app${'/(tabs)'}/payment` | `/app/payment`; params?: Router.UnknownInputParams; } | { pathname: `/app${'/(tabs)'}/profile` | `/app/profile`; params?: Router.UnknownInputParams; } | { pathname: `/app/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/verification`; params?: Router.UnknownOutputParams; } | { pathname: `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/app`; params?: Router.UnknownOutputParams; } | { pathname: `/app/login`; params?: Router.UnknownOutputParams; } | { pathname: `/app/matching`; params?: Router.UnknownOutputParams; } | { pathname: `/app/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/app/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/app/tracking`; params?: Router.UnknownOutputParams; } | { pathname: `/app/verification`; params?: Router.UnknownOutputParams; } | { pathname: `/app/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/app${'/(tabs)'}/activity` | `/app/activity`; params?: Router.UnknownOutputParams; } | { pathname: `/app${'/(tabs)'}` | `/app`; params?: Router.UnknownOutputParams; } | { pathname: `/app${'/(tabs)'}/payment` | `/app/payment`; params?: Router.UnknownOutputParams; } | { pathname: `/app${'/(tabs)'}/profile` | `/app/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/app/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/login${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/verification${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/app${`?${string}` | `#${string}` | ''}` | `/app/login${`?${string}` | `#${string}` | ''}` | `/app/matching${`?${string}` | `#${string}` | ''}` | `/app/settings${`?${string}` | `#${string}` | ''}` | `/app/signup${`?${string}` | `#${string}` | ''}` | `/app/tracking${`?${string}` | `#${string}` | ''}` | `/app/verification${`?${string}` | `#${string}` | ''}` | `/app/welcome${`?${string}` | `#${string}` | ''}` | `/app${'/(tabs)'}/activity${`?${string}` | `#${string}` | ''}` | `/app/activity${`?${string}` | `#${string}` | ''}` | `/app${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/app${`?${string}` | `#${string}` | ''}` | `/app${'/(tabs)'}/payment${`?${string}` | `#${string}` | ''}` | `/app/payment${`?${string}` | `#${string}` | ''}` | `/app${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/app/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/verification`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/app`; params?: Router.UnknownInputParams; } | { pathname: `/app/login`; params?: Router.UnknownInputParams; } | { pathname: `/app/matching`; params?: Router.UnknownInputParams; } | { pathname: `/app/settings`; params?: Router.UnknownInputParams; } | { pathname: `/app/signup`; params?: Router.UnknownInputParams; } | { pathname: `/app/tracking`; params?: Router.UnknownInputParams; } | { pathname: `/app/verification`; params?: Router.UnknownInputParams; } | { pathname: `/app/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/app${'/(tabs)'}/activity` | `/app/activity`; params?: Router.UnknownInputParams; } | { pathname: `/app${'/(tabs)'}` | `/app`; params?: Router.UnknownInputParams; } | { pathname: `/app${'/(tabs)'}/payment` | `/app/payment`; params?: Router.UnknownInputParams; } | { pathname: `/app${'/(tabs)'}/profile` | `/app/profile`; params?: Router.UnknownInputParams; } | `/app/+not-found` | { pathname: `/app/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
